1.4
bobtail-dev/bobtail pull request #85
Opened 2017-01-09 10:16 UTC by rmehlinger

Remove dead code
Consistently use `all()` instead of `raw()`
nullcheck map event handlers
fixed `ObsMap.has`
added `ObsMap.keys` and `ObsMap.values` utility functions

Finally, fleshed out `ObsArray` and `SrcArray` with reactive equivalents of most of the member methods of the native JavaScript Array class. In addition added some other useful methods that seemed like a good idea to have around:

`transform`: a replacement for the `rx.cellToArray rx.bind => @all()...` dance, which also avoids the creation of an unnecessary intermediate cell.
`move` and `swap`: Highly useful for UI work, e.g. with drag-and-drops, and more complicated than they seem at first glance.
`first` and `last`: Some simple syntactic sugar, a l'underscore.

2017-01-16 22:56 UTC, yang requested changes
I'd abandon this commit

2017-01-16 22:56 UTC, yang commented on bower.json
> +  "version": "1.3.3",
This already is at 1.3.3....

2017-01-16 22:56 UTC, yang commented on src/reactive.coffee
> +        target.refresh() if key of (additions ? {})
These should never be null

2017-01-16 23:05 UTC, yang requested changes

2017-01-16 23:05 UTC, yang commented on src/reactive.coffee
> -  nthWhere = (xs, n, f) ->
I would split these unrelated changes out to minimize noise

2017-01-16 23:05 UTC, yang commented on package.json
> +  "version": "1.4.0",
Why cut a new release?

Also, release bumps should always be in their own commit, not bundled with other code changes.

2017-01-16 23:05 UTC, yang commented on src/reactive.coffee
> +        sub(topCell)
Ditto as above

2017-01-16 23:05 UTC, yang commented on src/reactive.coffee
> +    transform: (f, diff) -> new DepArray (=> f @all()), diff
These all need to be deeply tested (specifying the behavior of incremental changes on the transforms)

2017-01-16 23:05 UTC, yang commented on src/reactive.coffee
> +      i = _(rx.snap => @all()).indexOf(x)
Why move to all()? Slower, and the original use of `raw()` was safe / non-mutating

Same various points below

Also really need to break these out into separate commits

2017-01-16 23:05 UTC, yang commented on src/reactive.coffee
> +    removeAll: (x) -> rx.transaction =>
Same with testing all of these

2017-01-16 23:05 UTC, yang commented on src/reactive.coffee
> +      recorder.sub (target) => rx.autoSub @onAdd, (additions) ->
Great catch

2017-01-17 05:37 UTC, rmehlinger commented on src/reactive.coffee
> +      i = _(rx.snap => @all()).indexOf(x)
`raw` already calls all. I'm not sure who made that change, but there seems to be no reason for its continued existence.

2017-01-17 05:41 UTC, rmehlinger commented on src/reactive.coffee
> +    transform: (f, diff) -> new DepArray (=> f @all()), diff
Yup, planning on giving them the same treatment as the `SrcArray` methods. By incremental changes, I assume you mean things like adding and removing one at a time?

2017-01-24 23:29 UTC, closed without merging